package agent

import (
	"github.com/vibe-menu/internal/realize/dag"
	"github.com/vibe-menu/internal/realize/memory"
	"github.com/vibe-menu/internal/realize/skills"
)

// Context bundles everything an agent needs for one task invocation.
type Context struct {
	Task           *dag.Task
	SkillDocs      []skills.Doc
	PreviousErrors string // non-empty on retry attempts
	// DependencyOutputs holds the files generated by upstream tasks that this
	// task depends on. Agents use this as shared memory to stay consistent with
	// the types, schemas, and interfaces already produced by the wider team.
	DependencyOutputs []*memory.TaskOutput
	// AttemptNumber is 0 for the first attempt and increments on each retry.
	// Used by prompt builders to prune context on retries (dependency outputs
	// are omitted after attempt 0 to avoid re-sending unchanged upstream context).
	AttemptNumber int
	// DepsContext is pre-computed dependency and library API reference text
	// for the task's technology stack. Injected into the system prompt to
	// prevent the agent from inventing module versions or non-existent types.
	DepsContext string
	// ExistingTypeRegistry is a snapshot of all exported types already committed
	// by upstream tasks, keyed by type name. Agents must import from the listed
	// package path instead of redefining the type. This prevents duplicate
	// interface/struct declarations across independently generated tasks.
	ExistingTypeRegistry map[string]memory.TypeEntry
}
