package agent

import (
	"github.com/vibe-menu/internal/realize/dag"
	"github.com/vibe-menu/internal/realize/memory"
	"github.com/vibe-menu/internal/realize/skills"
)

// Context bundles everything an agent needs for one task invocation.
type Context struct {
	Task           *dag.Task
	SkillDocs      []skills.Doc
	PreviousErrors string // non-empty on retry attempts
	// DependencyOutputs holds the files generated by upstream tasks that this
	// task depends on. Agents use this as shared memory to stay consistent with
	// the types, schemas, and interfaces already produced by the wider team.
	DependencyOutputs []*memory.TaskOutput
	// AttemptNumber is 0 for the first attempt and increments on each retry.
	// Used by prompt builders to prune context on retries (dependency outputs
	// are omitted after attempt 0 to avoid re-sending unchanged upstream context).
	AttemptNumber int
	// DepsContext is pre-computed dependency and library API reference text
	// for the task's technology stack. Injected into the system prompt to
	// prevent the agent from inventing module versions or non-existent types.
	DepsContext string
	// ExistingTypeRegistry is a snapshot of all exported types already committed
	// by upstream tasks, keyed by type name. Agents must import from the listed
	// package path instead of redefining the type. This prevents duplicate
	// interface/struct declarations across independently generated tasks.
	ExistingTypeRegistry map[string]memory.TypeEntry
	// AllConstructors is a snapshot of every constructor and factory signature
	// extracted from committed files at their original, untruncated content.
	// Injected into the prompt so agents (especially bootstrap wiring) call
	// constructors with the correct argument count and return signature, even
	// when the corresponding file excerpt was truncated by the memory budget.
	AllConstructors []memory.ConstructorSig
	// AllServiceMethods is a snapshot of every exported method signature on
	// service/repository structs. Like AllConstructors, these are extracted from
	// untruncated content at commit time, ensuring handler tasks generate
	// compatible method calls even when file excerpts are budget-limited.
	AllServiceMethods []memory.ServiceMethodSig
	// AllErrorSentinels is a snapshot of every exported Err* variable declaration
	// from upstream tasks. Injected into the prompt so agents use only defined
	// sentinel names and do not invent new ones (e.g. ErrAlreadyExists when the
	// plan task defined ErrUniqueConstraintViolation).
	AllErrorSentinels []memory.ErrorSentinel
	// InterfaceContracts is a snapshot of every exported Go interface extracted
	// from upstream tasks. Injected as a hard checklist in the prompt so
	// implementation tasks match interface method signatures exactly.
	InterfaceContracts []memory.InterfaceContract
	// CrossTaskIssues contains known cross-task build errors detected by
	// incremental compilation. Advisory context for downstream tasks.
	CrossTaskIssues string
	// BootstrapSkeleton is a deterministically generated main.go skeleton
	// with exact constructor calls. Only populated for bootstrap tasks.
	BootstrapSkeleton string
}

// Language returns the primary backend language from the task payload.
// Returns "" when no language can be determined (e.g. infra-only tasks).
func (c *Context) Language() string {
	if c.Task.Payload.Service != nil {
		return c.Task.Payload.Service.Language
	}
	if len(c.Task.Payload.AllServices) > 0 {
		return c.Task.Payload.AllServices[0].Language
	}
	if c.Task.Payload.Frontend != nil && c.Task.Payload.Frontend.Tech != nil {
		return c.Task.Payload.Frontend.Tech.Language
	}
	return ""
}
