package agent

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/vibe-menu/internal/realize/dag"
	"github.com/vibe-menu/internal/realize/skills"
)

// SystemPrompt builds the stable system prompt for a task kind.
// depsContext, if non-empty, is injected after the output format instructions
// to provide exact module versions and library API docs for the task's stack.
// The prompt is stable across retries so it benefits from prompt caching.
func SystemPrompt(kind dag.TaskKind, skillDocs []skills.Doc, depsContext string) string {
	var b strings.Builder

	b.WriteString(roleDescription(kind))
	b.WriteString("\n\n")
	b.WriteString(outputFormatInstructions())

	if depsContext != "" {
		b.WriteString("\n")
		b.WriteString(depsContext)
	}

	if len(skillDocs) > 0 {
		b.WriteString("\n\n## Technology Skill Guides\n\n")
		for _, doc := range skillDocs {
			b.WriteString(fmt.Sprintf("### %s\n\n%s\n\n", doc.Technology, doc.Content))
		}
	}

	return b.String()
}

// UserMessage builds the user turn message for an agent invocation.
func UserMessage(ac *Context) (string, error) {
	payloadJSON, err := json.Marshal(ac.Task.Payload)
	if err != nil {
		return "", fmt.Errorf("marshal payload: %w", err)
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("## Task: %s\n\n", ac.Task.Label))
	b.WriteString(fmt.Sprintf("Task ID: %s\nKind: %s\n", ac.Task.ID, ac.Task.Kind))
	if ac.Task.Payload.ModulePath != "" {
		b.WriteString(fmt.Sprintf("Module path: %s  ← use this EXACTLY as the Go module name in go.mod and all import paths\n", ac.Task.Payload.ModulePath))
	}
	b.WriteString("\n## Manifest Payload\n\n```json\n")
	b.Write(payloadJSON)
	b.WriteString("\n```\n")

	// Inject shared memory from completed upstream tasks.
	// On attempt 0: inject full type-signature excerpts so the agent knows what
	// types, schemas, and interfaces the rest of the team produced.
	// On retries: inject only a compact summary to avoid re-sending unchanged
	// upstream context — the agent only needs to fix the reported errors.
	if len(ac.DependencyOutputs) > 0 {
		if ac.AttemptNumber == 0 {
			b.WriteString("\n## Shared Team Context\n\n")
			b.WriteString("The following type signatures and interfaces were generated by upstream agents.\n")
			b.WriteString("You MUST use the same type names, module paths, import paths, and data shapes —\n")
			b.WriteString("do not redefine anything already declared below.\n\n")
			for _, dep := range ac.DependencyOutputs {
				b.WriteString(fmt.Sprintf("### From task: %s (%s)\n\n", dep.Label, dep.Kind))
				for _, f := range dep.Files {
					b.WriteString(fmt.Sprintf("#### `%s`\n\n", f.Path))
					b.WriteString("```")
					b.WriteString(fenceLanguage(f.Path))
					b.WriteString("\n")
					b.WriteString(f.Content)
					if f.Truncated {
						b.WriteString("\n// ... [truncated — use the types shown above]")
					}
					b.WriteString("\n```\n\n")
				}
			}
		} else {
			// Retry: just list upstream tasks by name to orient the agent without
			// re-spending tokens on content it already received on attempt 0.
			b.WriteString("\n## Shared Team Context (abbreviated)\n\n")
			b.WriteString("Upstream task outputs are unchanged — refer to your earlier context:\n\n")
			for _, dep := range ac.DependencyOutputs {
				b.WriteString(fmt.Sprintf("- %s (%s): %d file(s)\n", dep.Label, dep.Kind, len(dep.Files)))
			}
			b.WriteString("\n")
		}
	}

	if ac.PreviousErrors != "" {
		b.WriteString("\n## Previous Attempt Failed — Verification Errors\n\n")
		b.WriteString("The previous code generation attempt failed the following verification checks. ")
		b.WriteString("Analyze the errors, fix the issues, and regenerate all files completely.\n\n")
		b.WriteString("```\n")
		b.WriteString(ac.PreviousErrors)
		b.WriteString("\n```\n")
		if hints := errorPatternHints(ac.PreviousErrors); hints != "" {
			b.WriteString(hints)
		}
	}

	b.WriteString("\nGenerate the complete files for this task now.")
	return b.String(), nil
}

// fenceLanguage returns the markdown code fence language tag for a file path.
func fenceLanguage(path string) string {
	lower := strings.ToLower(path)
	switch {
	case strings.HasSuffix(lower, ".go"):
		return "go"
	case strings.HasSuffix(lower, ".ts") || strings.HasSuffix(lower, ".tsx"):
		return "typescript"
	case strings.HasSuffix(lower, ".proto"):
		return "protobuf"
	case strings.HasSuffix(lower, ".yaml") || strings.HasSuffix(lower, ".yml"):
		return "yaml"
	case strings.HasSuffix(lower, ".json"):
		return "json"
	case strings.HasSuffix(lower, ".py"):
		return "python"
	case strings.HasSuffix(lower, ".tf"):
		return "hcl"
	default:
		return ""
	}
}

// errorPatternHints inspects the verification error output and returns targeted
// guidance for common, well-understood failure modes. Returns empty string when
// no patterns are recognised.
func errorPatternHints(errors string) string {
	type pattern struct {
		needle string
		hint   string
	}
	patterns := []pattern{
		{
			"missing go.sum entry",
			"Go dependency issue: your go.mod `require` block is incomplete or uses wrong module paths. " +
				"The verifier runs `go mod tidy` automatically, but tidy needs the internet — ensure every " +
				"imported package appears in go.mod `require`. Double-check module paths (e.g. " +
				"`github.com/gofiber/fiber/v2`, not `github.com/gofiber/fiber`). " +
				"Regenerate go.mod with the exact, correct module paths for all imports in your generated files.",
		},
		{
			"cannot find module",
			"Module resolution failure: a package import path does not match any module in go.mod. " +
				"Verify the exact import path and version for every dependency, then include a complete go.mod.",
		},
		{
			"undefined:",
			"Undefined symbol: a referenced identifier is not declared in scope. " +
				"Check that all struct types, functions, and constants you reference are declared in the same " +
				"package or properly imported. Ensure all files that need each other are included in the output.",
		},
		{
			"cannot use",
			"Type mismatch: a value is being passed where an incompatible type is expected. " +
				"Verify struct field types and function signatures are consistent across files. " +
				"Pay special attention to pointer vs value types and interface implementations.",
		},
		{
			"declared and not used",
			"Unused variable: Go forbids declared-but-unused variables. Remove or use every declared variable.",
		},
		{
			"imported and not used",
			"Unused import: Go forbids imported-but-unused packages. Remove every import that is not referenced.",
		},
		{
			"does not implement",
			"Interface not satisfied: a concrete type is missing one or more methods required by the interface. " +
				"Check the interface definition and ensure the concrete type implements every method with " +
				"the exact signature (including pointer vs value receiver).",
		},
		{
			"syntax error",
			"Syntax error: the generated Go code is not valid. Check for mismatched braces, missing commas " +
				"in struct literals, or incomplete function bodies. Regenerate the affected files in full.",
		},
		{
			"gofmt",
			"Formatting issue: one or more files are not gofmt-clean. Use standard Go indentation (tabs) " +
				"and ensure the generated source passes `gofmt -l` without listing any files.",
		},
	}

	var matched []string
	for _, p := range patterns {
		if strings.Contains(errors, p.needle) {
			matched = append(matched, "- "+p.hint)
		}
	}
	if len(matched) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("\n## Targeted Fix Guidance\n\n")
	b.WriteString("Based on the errors above, pay special attention to:\n\n")
	for _, m := range matched {
		b.WriteString(m + "\n")
	}
	return b.String()
}

// outputFormatInstructions describes the required response format to the agent.
func outputFormatInstructions() string {
	return `## Output Format

You MUST respond with a <files> block containing a JSON array of file objects.
Each file object has a "path" (relative to the project output directory) and "content" (complete file content).

Example:
<files>
[
  {
    "path": "services/user-api/main.go",
    "content": "package main\n\nimport ..."
  },
  {
    "path": "services/user-api/Dockerfile",
    "content": "FROM golang:<version>-alpine\n..."
  }
]
</files>

Rules:
- Always use the <files>...</files> XML tags — do NOT use markdown code fences for the file list.
- Include ALL files needed for the task to be complete and buildable.
- File paths must use forward slashes and be relative (no leading slash).
- File content must be complete — no placeholders, no TODO comments for required logic.
- For TypeScript/JS: include package.json with pinned dependency versions and all necessary config files.
- For Terraform: include all .tf files needed to apply successfully.
- Generated code must pass the relevant linter/build check for its language.

### Go-Specific Rules (CRITICAL)
- If a go.mod was provided in the "Shared Team Context" or "LOCKED DEPENDENCIES" section,
  DO NOT include go.mod or go.sum in your output. The build system manages dependencies.
- If you MUST generate go.mod (plan/skeleton task only), use EXACTLY the module paths and
  versions from the "Dependency & API Reference" section. Never invent version strings.
- All Go regex patterns MUST use backtick raw strings, not double-quoted strings:
  CORRECT: regexp.MustCompile(` + "`" + `\d{4}-\d{2}-\d{2}` + "`" + `)
  WRONG:   regexp.MustCompile("\d{4}-\d{2}-\d{2}")    // invalid escape sequences
  WRONG:   regexp.MustCompile("\\d{4}-\\d{2}-\\d{2}") // fragile double-escaping
- All Go code MUST be gofmt-clean — use tabs for indentation, not spaces.
- Always generate _test.go files alongside every service, handler, and repository file.
  Use table-driven tests covering happy path, error cases, and edge cases.
- No hardcoded secrets: read all credentials from environment variables with a startup check.
- Apply idiomatic Go: constructor injection, small focused interfaces, error wrapping with
  fmt.Errorf("context: %w", err). Never ignore errors.
- Use the EXACT library APIs documented in the "Dependency & API Reference" section.
  Do NOT invent types or functions that are not listed there.

### npm / Node.js Rules (CRITICAL)
- Use 'npm install' NOT 'npm ci' in Dockerfiles and README instructions — package-lock.json
  is generated at runtime, not by the pipeline. npm ci will FAIL without a pre-existing lockfile.
- Config files: use next.config.mjs (ESM) — works universally across Next.js versions.
  next.config.ts is only supported from Next.js 15.3+.
- Always use EXACTLY the versions from the "Infrastructure & Dependency Reference" section.
  Do NOT guess or use @latest for any package.`
}
