package agent

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/vibe-menu/internal/realize/dag"
	"github.com/vibe-menu/internal/realize/skills"
)

// SystemPrompt builds the stable system prompt for a task kind.
// depsContext, if non-empty, is injected after the output format instructions
// to provide exact module versions and library API docs for the task's stack.
// The prompt is stable across retries so it benefits from prompt caching.
func SystemPrompt(kind dag.TaskKind, skillDocs []skills.Doc, depsContext string) string {
	var b strings.Builder

	b.WriteString(roleDescription(kind))
	b.WriteString("\n\n")
	b.WriteString(outputFormatInstructions())

	if depsContext != "" {
		b.WriteString("\n")
		b.WriteString(depsContext)
	}

	if len(skillDocs) > 0 {
		b.WriteString("\n\n## Technology Skill Guides\n\n")
		for _, doc := range skillDocs {
			b.WriteString(fmt.Sprintf("### %s\n\n%s\n\n", doc.Technology, doc.Content))
		}
	}

	return b.String()
}

// UserMessage builds the user turn message for an agent invocation.
func UserMessage(ac *Context) (string, error) {
	payloadJSON, err := json.Marshal(ac.Task.Payload)
	if err != nil {
		return "", fmt.Errorf("marshal payload: %w", err)
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("## Task: %s\n\n", ac.Task.Label))
	b.WriteString(fmt.Sprintf("Task ID: %s\nKind: %s\n", ac.Task.ID, ac.Task.Kind))
	modulePath := ac.Task.Payload.ModulePath
	outputDir := ac.Task.Payload.OutputDir
	if modulePath != "" {
		b.WriteString(fmt.Sprintf("Module path: **%s**  ← REQUIRED: use this EXACTLY as the Go module name in go.mod and ALL internal import paths. Never substitute a placeholder like \"github.com/your-org/\" or \"github.com/your-company/\".\n", modulePath))
		// Explicitly warn when output directory differs from module path.
		// Agents sometimes use the output directory name as the import prefix, which
		// causes "package X is not in std" errors (e.g. "backend/internal/domain"
		// when the correct import is "monolith/internal/domain").
		if outputDir != "" && outputDir != "." && outputDir != modulePath {
			b.WriteString(fmt.Sprintf("⚠ Output directory (**%s**) is the FILESYSTEM location only — it is NOT the Go module name. Import internal packages as `\"%s/internal/...\"`, NEVER as `\"%s/internal/...\"`.\n", outputDir, modulePath, outputDir))
		}
	}
	if desc := ac.Task.Payload.Description; desc != "" {
		b.WriteString(fmt.Sprintf("\n## Project Context\n\n%s\n", desc))
	}

	b.WriteString("\n## Manifest Payload\n\n```json\n")
	b.Write(payloadJSON)
	b.WriteString("\n```\n")

	// Cross-task type registry: list all types already defined by upstream tasks.
	// Injected on attempt 0 only — on retries the registry is stable and the agent
	// already received it in the earlier attempt.
	if len(ac.ExistingTypeRegistry) > 0 && ac.AttemptNumber == 0 {
		b.WriteString("\n## Cross-Task Type Registry — DO NOT REDEFINE\n\n")
		b.WriteString("These types are already defined by upstream tasks. ")
		b.WriteString("**Import them from the listed package — do NOT redeclare them in your output.**\n")
		b.WriteString("Redefining these types will cause a `redeclared in this block` compilation error.\n\n")
		names := make([]string, 0, len(ac.ExistingTypeRegistry))
		for name := range ac.ExistingTypeRegistry {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			entry := ac.ExistingTypeRegistry[name]
			if entry.Package != "" {
				importPath := entry.Package
				if modulePath != "" {
					importPath = modulePath + "/" + entry.Package
				}
				b.WriteString(fmt.Sprintf("- `%s` — `%s` — import as `\"%s\"`\n", name, entry.File, importPath))
				if entry.Definition != "" {
					b.WriteString("  ```go\n")
					for _, dl := range strings.Split(strings.TrimRight(entry.Definition, "\n"), "\n") {
						b.WriteString("  " + dl + "\n")
					}
					b.WriteString("  ```\n")
				}
			}
		}
		b.WriteString("\n")
	}

	// Inject shared memory from completed upstream tasks.
	// On attempt 0: inject full type-signature excerpts so the agent knows what
	// types, schemas, and interfaces the rest of the team produced.
	// On retries: inject only a compact summary to avoid re-sending unchanged
	// upstream context — the agent only needs to fix the reported errors.
	if len(ac.DependencyOutputs) > 0 {
		if ac.AttemptNumber == 0 {
			b.WriteString("\n## Shared Team Context\n\n")
			b.WriteString("The following type signatures and interfaces were generated by upstream agents.\n")
			b.WriteString("You MUST use the same type names, module paths, import paths, and data shapes —\n")
			b.WriteString("do not redefine anything already declared below.\n\n")
			// Add language-specific import path guidance so agents don't confuse the
			// filesystem output directory with the language module/package namespace.
			if modulePath != "" {
				b.WriteString(fmt.Sprintf("**Go import paths:** All upstream files belong to module `%s`.\n", modulePath))
				b.WriteString(fmt.Sprintf("Import by prepending the module name: `internal/domain/user.go` → `import \"%s/internal/domain\"`,\n", modulePath))
				b.WriteString(fmt.Sprintf("`internal/repository/interfaces.go` → `import \"%s/internal/repository\"`.\n", modulePath))
				if outputDir != "" && outputDir != "." && outputDir != modulePath {
					b.WriteString(fmt.Sprintf("NEVER use the output directory `%s` as an import prefix — `\"%s/internal/...\"` is WRONG.\n", outputDir, outputDir))
				}
				b.WriteString("\n")
			}
			for _, dep := range ac.DependencyOutputs {
				b.WriteString(fmt.Sprintf("### From task: %s (%s)\n\n", dep.Label, dep.Kind))
				for _, f := range dep.Files {
					b.WriteString(fmt.Sprintf("#### `%s`\n\n", f.Path))
					b.WriteString("```")
					b.WriteString(fenceLanguage(f.Path))
					b.WriteString("\n")
					b.WriteString(f.Content)
					if f.Truncated {
						b.WriteString("\n// ... [truncated — use the types shown above]")
					}
					b.WriteString("\n```\n\n")
				}
			}
		} else {
			// Retry: just list upstream tasks by name to orient the agent without
			// re-spending tokens on content it already received on attempt 0.
			b.WriteString("\n## Shared Team Context (abbreviated)\n\n")
			b.WriteString("Upstream task outputs are unchanged — refer to your earlier context:\n\n")
			for _, dep := range ac.DependencyOutputs {
				b.WriteString(fmt.Sprintf("- %s (%s): %d file(s)\n", dep.Label, dep.Kind, len(dep.Files)))
			}
			b.WriteString("\n")
		}
	}

	// Inject constructor signatures from shared memory. These are extracted at
	// commit time from the full, untruncated file content, so they are never lost
	// to excerpt truncation. Covers a broader set of naming conventions than the
	// older excerpt-based scan (New*, Make*, Create*, Build*, Open*, Must*, and
	// method receivers).
	if len(ac.AllConstructors) > 0 && ac.AttemptNumber == 0 {
		b.WriteString("\n## Critical Constructor Signatures\n\n")
		b.WriteString("Call these constructors/factories with the **exact** signature shown.\n")
		b.WriteString("The `// from:` comment tells you where to import from:\n")
		b.WriteString("- Go: strip filename → `internal/repository/postgres/user.go` → `import \"{module_path}/internal/repository/postgres\"`\n")
		b.WriteString("- TypeScript: use relative import `./repository/user.repository`\n")
		b.WriteString("- Python: use dotted module path `app.repository.user_repository`\n\n")
		b.WriteString("```\n")
		prevFile := ""
		for _, c := range ac.AllConstructors {
			if c.File != prevFile {
				if prevFile != "" {
					b.WriteString("\n")
				}
				b.WriteString("// from: " + c.File + "\n")
				prevFile = c.File
			}
			b.WriteString(c.Signature + "\n")
		}
		b.WriteString("```\n")
	}

	if ac.PreviousErrors != "" {
		b.WriteString("\n## Previous Attempt Failed — Verification Errors\n\n")
		b.WriteString("The previous code generation attempt failed the following verification checks. ")
		b.WriteString("Analyze the errors, fix the issues, and regenerate all files completely.\n\n")
		b.WriteString("```\n")
		b.WriteString(ac.PreviousErrors)
		b.WriteString("\n```\n")
		if hints := errorPatternHints(ac.PreviousErrors); hints != "" {
			b.WriteString(hints)
		}
	}

	b.WriteString("\nGenerate the complete files for this task now.")
	return b.String(), nil
}

// fenceLanguage returns the markdown code fence language tag for a file path.
func fenceLanguage(path string) string {
	lower := strings.ToLower(path)
	switch {
	case strings.HasSuffix(lower, ".go"):
		return "go"
	case strings.HasSuffix(lower, ".ts") || strings.HasSuffix(lower, ".tsx"):
		return "typescript"
	case strings.HasSuffix(lower, ".proto"):
		return "protobuf"
	case strings.HasSuffix(lower, ".yaml") || strings.HasSuffix(lower, ".yml"):
		return "yaml"
	case strings.HasSuffix(lower, ".json"):
		return "json"
	case strings.HasSuffix(lower, ".py"):
		return "python"
	case strings.HasSuffix(lower, ".tf"):
		return "hcl"
	default:
		return ""
	}
}

// errorPatternHints inspects the verification error output and returns targeted
// guidance for common, well-understood failure modes. Returns empty string when
// no patterns are recognised.
func errorPatternHints(errors string) string {
	var matched []string

	// Extract specific missing method names from "does not implement" errors.
	// Go compiler format: "*ConcreteType does not implement Interface (missing method MethodName)"
	if strings.Contains(errors, "does not implement") {
		missingMethodRe := regexp.MustCompile(`(\*?\w+) does not implement (\w+) \(missing method (\w+)\)`)
		for _, m := range missingMethodRe.FindAllStringSubmatch(errors, -1) {
			concrete, iface, method := m[1], m[2], m[3]
			matched = append(matched,
				fmt.Sprintf("- Interface not satisfied: `%s` is missing method `%s` required by `%s`. "+
					"Find the interface definition in the Shared Team Context (interfaces.go) and implement "+
					"**every** method listed — do not truncate or omit any. Add `%s` with the EXACT "+
					"signature shown in the interface.", concrete, method, iface, method))
		}
		// If regex didn't match (unusual format), fall through to the generic pattern below.
	}

	// Extract specific undefined symbol names from "undefined:" errors.
	// Go compiler format: "undefined: symbolName"
	if strings.Contains(errors, "undefined:") {
		undefinedRe := regexp.MustCompile(`undefined: (\w+)`)
		seen := make(map[string]bool)
		for _, m := range undefinedRe.FindAllStringSubmatch(errors, -1) {
			sym := m[1]
			if seen[sym] {
				continue
			}
			seen[sym] = true
			matched = append(matched,
				fmt.Sprintf("- Symbol `%s` is undefined. Add a top-level import for the package that "+
					"exports `%s` (e.g. `\"net/http\"` for `http.*`, `\"context\"` for `context.*`, "+
					"`\"fmt\"` for `fmt.*`). Every referenced symbol must have a corresponding `import` "+
					"line in the same file — the compiler never resolves imports automatically.", sym, sym))
		}
	}

	type pattern struct {
		needle string
		hint   string
	}
	patterns := []pattern{
		{
			"missing go.sum entry",
			"Go dependency issue: your go.mod `require` block is incomplete or uses wrong module paths. " +
				"The verifier runs `go mod tidy` automatically, but tidy needs the internet — ensure every " +
				"imported package appears in go.mod `require`. Double-check module paths (e.g. " +
				"`github.com/gofiber/fiber/v2`, not `github.com/gofiber/fiber`). " +
				"Regenerate go.mod with the exact, correct module paths for all imports in your generated files.",
		},
		{
			"cannot find module",
			"Module resolution failure: a package import path does not match any module in go.mod. " +
				"Verify the exact import path and version for every dependency, then include a complete go.mod.",
		},
		{
			"undefined:",
			"Undefined symbol: check that all referenced identifiers are either declared in the same " +
				"package or imported. Every file must have a complete import block — the compiler does not " +
				"auto-resolve missing imports. See the specific symbol hints above for targeted guidance.",
		},
		{
			"cannot use",
			"Type mismatch: a value is being passed where an incompatible type is expected. " +
				"Verify struct field types and function signatures are consistent across files. " +
				"Pay special attention to pointer vs value types and interface implementations.",
		},
		{
			"declared and not used",
			"Unused variable: Go forbids declared-but-unused variables. Remove or use every declared variable.",
		},
		{
			"imported and not used",
			"Unused import: Go forbids imported-but-unused packages. Remove every import that is not referenced.",
		},
		{
			"does not implement",
			"Interface not satisfied: a concrete type is missing one or more required methods. " +
				"Find the interface definition in Shared Team Context and implement EVERY method listed — " +
				"never truncate or omit any. See the specific missing-method hints above for details.",
		},
		{
			"syntax error",
			"Syntax error: the generated Go code is not valid. Check for mismatched braces, missing commas " +
				"in struct literals, or incomplete function bodies. Regenerate the affected files in full.",
		},
		{
			"non-declaration statement outside function body",
			"Truncated interface declaration: a fragment like `, error)` at the top level means the " +
				"`type InterfaceName interface {` opening line and first method signature were cut off. " +
				"Regenerate the affected file in FULL:\n" +
				"  1. Every interface MUST start with `type X interface {`\n" +
				"  2. ALL methods must have COMPLETE signatures (no truncation, no `...` placeholders)\n" +
				"  3. interfaces.go contains ONLY interface type declarations — " +
				"NO `func` implementations, NO struct bodies, NO constructor functions.\n" +
				"Use the EXACT method signatures and return types from the " +
				"'Dependency & API Reference' section — never substitute `interface{}` " +
				"for a library-specific return type.",
		},
		{
			"gofmt",
			"Formatting issue: one or more files are not gofmt-clean. Use standard Go indentation (tabs) " +
				"and ensure the generated source passes `gofmt -l` without listing any files.",
		},
		{
			"has no field named",
			"Struct field mismatch: you are accessing a field that does not exist on the type. " +
				"Check the exact struct definition in the Shared Team Context above — do not guess field names. " +
				"Common cause: using a shorthand like resp.Email when the actual field is nested (resp.User.Email), " +
				"or the struct was renamed by an upstream task.",
		},
		{
			"not enough return values",
			"Return arity mismatch: a function returns fewer values than the caller expects. " +
				"Check the Critical Constructor Signatures and Shared Team Context — a New* constructor " +
				"likely changed to return an additional error value. Update the call site to handle all return values.",
		},
		{
			"too many return values",
			"Return arity mismatch: a function returns more values than the caller expects. " +
				"Check the function's actual signature in the Shared Team Context above.",
		},
		{
			"too many arguments in call to",
			"Argument count mismatch: you are passing MORE arguments than the function accepts. " +
				"Check the EXACT constructor/function signature in 'Critical Constructor Signatures'. " +
				"Common causes: (1) passing an extra config string, logger, or dependency not in the real " +
				"constructor signature; (2) using a different version of the constructor. " +
				"Use ONLY the parameters listed — do not add extras that are not shown.",
		},
		{
			"not enough arguments in call to",
			"Argument count mismatch: you are passing FEWER arguments than the function requires. " +
				"Check the EXACT constructor/function signature in 'Critical Constructor Signatures'. " +
				"The function likely requires more parameters than you are providing.",
		},
		{
			"array type uuid.UUID",
			"UUID type mismatch: uuid.UUID is an array type ([16]byte) and cannot be used directly as string. " +
				"Convert to string using the .String() method: `user.ID.String()` instead of `user.ID`. " +
				"This applies everywhere a uuid.UUID value is passed to a function expecting string, " +
				"including JWT claims (`claims[\"sub\"] = user.ID.String()`), DB queries, and helper functions.",
		},
		{
			"variable of type bool) as string",
			"Type mismatch in struct literal: a bool field is being assigned where string is expected. " +
				"PREFERRED FIX: change the response struct field type to bool — Go's encoding/json handles bool correctly. " +
				"If you must keep string: convert with strconv.FormatBool(value). " +
				"Response structs should mirror domain field types (bool for bool, time.Time for timestamps) — " +
				"do NOT convert every field to string.",
		},
		{
			`variable of struct type "time".Time) as string`,
			"Type mismatch in struct literal: a time.Time field is being assigned where string is expected. " +
				"PREFERRED FIX: change the response struct field type to time.Time — encoding/json serializes " +
				"time.Time as RFC 3339 automatically, which is correct for API responses. " +
				"If you must keep string: convert with value.Format(time.RFC3339).",
		},
		{
			"unexpected keyword import",
			"Syntax error: an import statement appeared inside a function body — this is not valid Go. " +
				"Import statements must appear at the top of the file in the import block, never inside functions. " +
				"Move any needed imports to the top-level import block and remove them from inside functions.",
		},
		{
			"ConnectTimeout undefined",
			"pgxpool v5 API change: pgxpool.Config does NOT have a ConnectTimeout field — it was removed in v5. " +
				"Remove any `config.ConnectTimeout = ...` line. To limit connection time, pass a context with " +
				"deadline to pgxpool.NewWithConfig: `ctx, cancel := context.WithTimeout(ctx, 10*time.Second)`. " +
				"Valid pool config fields: MaxConns, MinConns, MaxConnLifetime, MaxConnIdleTime, HealthCheckPeriod.",
		},
		{
			"multiple-value",
			"Multi-return handling: a function returning multiple values (e.g. value, error) is being " +
				"used in a single-value context. Assign all return values explicitly: " +
				"svc, err := NewService(...); if err != nil { ... }",
		},
		{
			"cannot find module providing",
			"Unknown import path: the imported package does not match any module in go.mod. " +
				"Verify you are using the exact module path from the 'Module path:' field at the top of this task, " +
				"not a placeholder like 'github.com/your-org/' or 'github.com/your-company/'. " +
				"All internal packages must be imported as '{module_path}/internal/...'.",
		},
	}

	for _, p := range patterns {
		if strings.Contains(errors, p.needle) {
			matched = append(matched, "- "+p.hint)
		}
	}
	if len(matched) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("\n## Targeted Fix Guidance\n\n")
	b.WriteString("Based on the errors above, pay special attention to:\n\n")
	for _, m := range matched {
		b.WriteString(m + "\n")
	}
	return b.String()
}

// outputFormatInstructions describes the required response format to the agent.
func outputFormatInstructions() string {
	return "## Module/Package Namespace vs Output Directory\n\n" +
		"CRITICAL: The filesystem output directory and the language module/package namespace are DIFFERENT things.\n" +
		"The OutputDir in the manifest payload tells you WHERE to put files on disk — it is NOT the import namespace.\n\n" +
		"Language rules:\n" +
		"- Go: module name is in go.mod (e.g. \"monolith\"). Import as \"monolith/internal/domain\", NEVER as \"backend/internal/domain\".\n" +
		"- Python: package root is the name in setup.py/pyproject.toml (e.g. \"app\"). Import as \"from app.domain import User\", not \"from backend.domain\".\n" +
		"- TypeScript: use tsconfig path aliases (e.g. \"@/\"). Import as \"@/domain/User\", not relative paths through the output dir.\n" +
		"- Java: use the groupId.artifactId base package (e.g. \"com.example.app\"). Import \"com.example.app.domain.User\", not \"backend.domain.User\".\n\n" +
		`## Output Format

You MUST respond with a <files> block containing a JSON array of file objects.
Each file object has a "path" (relative to YOUR component's directory) and "content" (complete file content).
The pipeline places your files under the correct subdirectory automatically — use component-relative paths
like "go.mod", "internal/service/user.go", "src/components/Button.tsx". Do NOT prefix paths with
directory names like "backend/", "frontend/", or "services/user-api/" — those are added by the pipeline.

EXCEPTION — infra.docker task: this task outputs files for the entire project from the project root.
It has no component directory, so paths MUST include the service subdirectory prefix:
  "backend/Dockerfile", "frontend/Dockerfile", "backend/.air.toml", "docker-compose.yml", etc.
See the Role section for full path rules when you are the infra.docker task.

Example:
<files>
[
  {
    "path": "main.go",
    "content": "package main\n\nimport ..."
  },
  {
    "path": "internal/domain/user.go",
    "content": "package domain\n\n..."
  }
]
</files>

Rules:
- Always use the <files>...</files> XML tags — do NOT use markdown code fences for the file list.
- Include ALL files needed for the task to be complete and buildable.
- File paths must use forward slashes and be relative (no leading slash).
- File content must be complete — no placeholders, no TODO comments for required logic.
- For TypeScript/JS: include package.json with pinned dependency versions and all necessary config files.
- For Terraform: include all .tf files needed to apply successfully.
- Generated code must pass the relevant linter/build check for its language.

### Go-Specific Rules (CRITICAL)
- If a go.mod was provided in the "Shared Team Context" or "LOCKED DEPENDENCIES" section,
  DO NOT include go.mod or go.sum in your output. The build system manages dependencies.
- If you MUST generate go.mod (plan/skeleton task only), use EXACTLY the module paths and
  versions from the "Dependency & API Reference" section. Never invent version strings.
- All Go regex patterns MUST use backtick raw strings, not double-quoted strings:
  CORRECT: regexp.MustCompile(` + "`" + `\d{4}-\d{2}-\d{2}` + "`" + `)
  WRONG:   regexp.MustCompile("\d{4}-\d{2}-\d{2}")    // invalid escape sequences
  WRONG:   regexp.MustCompile("\\d{4}-\\d{2}-\\d{2}") // fragile double-escaping
- All Go code MUST be gofmt-clean — use tabs for indentation, not spaces.
- Always generate _test.go files alongside every service, handler, and repository file.
  Use table-driven tests covering happy path, error cases, and edge cases.
- No hardcoded secrets: read all credentials from environment variables with a startup check.
- Apply idiomatic Go: constructor injection, small focused interfaces, error wrapping with
  fmt.Errorf("context: %w", err). Never ignore errors.
- Use the EXACT library APIs documented in the "Dependency & API Reference" section.
  Do NOT invent types or functions that are not listed there.

### npm / Node.js Rules (CRITICAL)
- Use 'npm install' NOT 'npm ci' in Dockerfiles and README instructions — package-lock.json
  is generated at runtime, not by the pipeline. npm ci will FAIL without a pre-existing lockfile.
- Config files: use next.config.mjs (ESM) — works universally across Next.js versions.
  next.config.ts is only supported from Next.js 15.3+.
- Always use EXACTLY the versions from the "Infrastructure & Dependency Reference" section.
  Do NOT guess or use @latest for any package.

### Architecture-Specific Directory Layout

The arch_pattern in your payload determines the expected project structure. Use this as a
reference when choosing file paths — your OutputDir prefix is added by the pipeline automatically.

Monolith (with frontend):
  backend/          ← OutputDir for backend tasks; go.mod lives here
    main.go
    Dockerfile      ← infra.docker task (path: "backend/Dockerfile")
    .air.toml       ← infra.docker task (path: "backend/.air.toml")
    .dockerignore   ← infra.docker task (path: "backend/.dockerignore")
    internal/
      domain/       ← data schemas task
      contracts/    ← contracts task (Go types)
      repository/
      service/
      handler/
    db/migrations/
  frontend/         ← OutputDir for frontend task
    Dockerfile      ← infra.docker task (path: "frontend/Dockerfile")
  docker-compose.yml  ← infra.docker task (path: "docker-compose.yml")
  openapi.yaml        ← contracts task (spec, at project root)

Monolith (no frontend):
  .                 ← OutputDir is "." for all backend tasks
    main.go
    go.mod
    internal/
      domain/
      contracts/
      repository/
      service/
      handler/

Modular Monolith:
  backend/ (or root)
    internal/
      modules/{module-name}/
        domain/
        repository/
        service/
        handler/
      router/       ← single router wiring all modules

Microservices / Event-Driven / Hybrid:
  services/{name}/  ← OutputDir per service; each has its own go.mod
    internal/
      domain/
      repository/
      service/
      handler/
  shared/           ← OutputDir for contracts task
    contracts/      ← shared Go types (package contracts)
    contracts/openapi.yaml
  frontend/
  docker-compose.yml`
}
