package agent

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/vibe-mvp/internal/realize/dag"
	"github.com/vibe-mvp/internal/realize/skills"
)

// SystemPrompt builds the stable system prompt for a task kind.
// The prompt is stable across retries so it benefits from prompt caching.
func SystemPrompt(kind dag.TaskKind, skillDocs []skills.Doc) string {
	var b strings.Builder

	b.WriteString(roleDescription(kind))
	b.WriteString("\n\n")
	b.WriteString(outputFormatInstructions())

	if len(skillDocs) > 0 {
		b.WriteString("\n\n## Technology Skill Guides\n\n")
		for _, doc := range skillDocs {
			b.WriteString(fmt.Sprintf("### %s\n\n%s\n\n", doc.Technology, doc.Content))
		}
	}

	return b.String()
}

// UserMessage builds the user turn message for an agent invocation.
func UserMessage(ac *Context) (string, error) {
	payloadJSON, err := json.MarshalIndent(ac.Task.Payload, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal payload: %w", err)
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("## Task: %s\n\n", ac.Task.Label))
	b.WriteString(fmt.Sprintf("Task ID: %s\nKind: %s\n\n", ac.Task.ID, ac.Task.Kind))
	b.WriteString("## Manifest Payload\n\n```json\n")
	b.Write(payloadJSON)
	b.WriteString("\n```\n")

	// Inject shared memory from completed upstream tasks so this agent knows
	// exactly what types, schemas, and interfaces the rest of the team produced.
	if len(ac.DependencyOutputs) > 0 {
		b.WriteString("\n## Shared Team Context\n\n")
		b.WriteString("The following files were already generated by upstream agents in this project.\n")
		b.WriteString("You MUST use the same type names, module paths, import paths, and data shapes —\n")
		b.WriteString("do not redefine anything already declared below.\n\n")
		for _, dep := range ac.DependencyOutputs {
			b.WriteString(fmt.Sprintf("### From task: %s (%s)\n\n", dep.Label, dep.Kind))
			for _, f := range dep.Files {
				b.WriteString(fmt.Sprintf("#### `%s`\n\n", f.Path))
				// Infer a code fence language from file extension.
				b.WriteString("```")
				b.WriteString(fenceLanguage(f.Path))
				b.WriteString("\n")
				b.WriteString(f.Content)
				if f.Truncated {
					b.WriteString("\n// ... [file truncated — use the types shown above]")
				}
				b.WriteString("\n```\n\n")
			}
		}
	}

	if ac.PreviousErrors != "" {
		b.WriteString("\n## Previous Attempt Failed — Verification Errors\n\n")
		b.WriteString("The previous code generation attempt failed the following verification checks. ")
		b.WriteString("Analyze the errors, fix the issues, and regenerate all files completely.\n\n")
		b.WriteString("```\n")
		b.WriteString(ac.PreviousErrors)
		b.WriteString("\n```\n")
		if hints := errorPatternHints(ac.PreviousErrors); hints != "" {
			b.WriteString(hints)
		}
	}

	b.WriteString("\nGenerate the complete files for this task now.")
	return b.String(), nil
}

// fenceLanguage returns the markdown code fence language tag for a file path.
func fenceLanguage(path string) string {
	lower := strings.ToLower(path)
	switch {
	case strings.HasSuffix(lower, ".go"):
		return "go"
	case strings.HasSuffix(lower, ".ts") || strings.HasSuffix(lower, ".tsx"):
		return "typescript"
	case strings.HasSuffix(lower, ".proto"):
		return "protobuf"
	case strings.HasSuffix(lower, ".yaml") || strings.HasSuffix(lower, ".yml"):
		return "yaml"
	case strings.HasSuffix(lower, ".json"):
		return "json"
	case strings.HasSuffix(lower, ".py"):
		return "python"
	case strings.HasSuffix(lower, ".tf"):
		return "hcl"
	default:
		return ""
	}
}

// errorPatternHints inspects the verification error output and returns targeted
// guidance for common, well-understood failure modes. Returns empty string when
// no patterns are recognised.
func errorPatternHints(errors string) string {
	type pattern struct {
		needle string
		hint   string
	}
	patterns := []pattern{
		{
			"missing go.sum entry",
			"Go dependency issue: your go.mod `require` block is incomplete or uses wrong module paths. " +
				"The verifier runs `go mod tidy` automatically, but tidy needs the internet — ensure every " +
				"imported package appears in go.mod `require`. Double-check module paths (e.g. " +
				"`github.com/gofiber/fiber/v2`, not `github.com/gofiber/fiber`). " +
				"Regenerate go.mod with the exact, correct module paths for all imports in your generated files.",
		},
		{
			"cannot find module",
			"Module resolution failure: a package import path does not match any module in go.mod. " +
				"Verify the exact import path and version for every dependency, then include a complete go.mod.",
		},
		{
			"undefined:",
			"Undefined symbol: a referenced identifier is not declared in scope. " +
				"Check that all struct types, functions, and constants you reference are declared in the same " +
				"package or properly imported. Ensure all files that need each other are included in the output.",
		},
		{
			"cannot use",
			"Type mismatch: a value is being passed where an incompatible type is expected. " +
				"Verify struct field types and function signatures are consistent across files. " +
				"Pay special attention to pointer vs value types and interface implementations.",
		},
		{
			"declared and not used",
			"Unused variable: Go forbids declared-but-unused variables. Remove or use every declared variable.",
		},
		{
			"imported and not used",
			"Unused import: Go forbids imported-but-unused packages. Remove every import that is not referenced.",
		},
		{
			"does not implement",
			"Interface not satisfied: a concrete type is missing one or more methods required by the interface. " +
				"Check the interface definition and ensure the concrete type implements every method with " +
				"the exact signature (including pointer vs value receiver).",
		},
		{
			"syntax error",
			"Syntax error: the generated Go code is not valid. Check for mismatched braces, missing commas " +
				"in struct literals, or incomplete function bodies. Regenerate the affected files in full.",
		},
		{
			"gofmt",
			"Formatting issue: one or more files are not gofmt-clean. Use standard Go indentation (tabs) " +
				"and ensure the generated source passes `gofmt -l` without listing any files.",
		},
	}

	var matched []string
	for _, p := range patterns {
		if strings.Contains(errors, p.needle) {
			matched = append(matched, "- "+p.hint)
		}
	}
	if len(matched) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("\n## Targeted Fix Guidance\n\n")
	b.WriteString("Based on the errors above, pay special attention to:\n\n")
	for _, m := range matched {
		b.WriteString(m + "\n")
	}
	return b.String()
}

// roleDescription returns a role/persona description for the given task kind.
func roleDescription(kind dag.TaskKind) string {
	descriptions := map[dag.TaskKind]string{
		dag.TaskKindDataSchemas:     "You are an expert database architect. Generate production-quality ORM models, domain schema definitions, and SQL DDL based on the provided domain definitions.",
		dag.TaskKindDataMigrations:  "You are an expert database engineer. Generate database migration files that create the tables, indexes, and constraints described in the domain definitions.",
		dag.TaskKindService:         "You are an expert backend engineer. Generate a complete, production-quality service implementation including handlers, middleware, routing, and configuration. Generate _test.go files for all handlers, services, and repositories using table-driven tests. All config via environment variables; no secrets in code.",
		dag.TaskKindAuth:            "You are an expert security engineer. Generate authentication and authorization middleware, token handling, and identity integration code.",
		dag.TaskKindMessaging:       "You are an expert distributed systems engineer. Generate message broker configuration, event producer/consumer boilerplate, and event schema definitions.",
		dag.TaskKindGateway:         "You are an expert platform engineer. Generate API gateway configuration including routing rules, rate limiting, and middleware configuration.",
		dag.TaskKindContracts:       "You are an expert API designer. Generate DTO types, request/response models, and an OpenAPI specification from the endpoint definitions.",
		dag.TaskKindFrontend:        "You are an expert frontend engineer. Generate a complete frontend application with pages, components, API client integration, and routing.",
		dag.TaskKindInfraDocker:     "You are an expert DevOps engineer. Generate Dockerfiles and docker-compose configuration for all services.",
		dag.TaskKindInfraTerraform:  "You are an expert infrastructure engineer. Generate IaC configuration files (Terraform/Pulumi) for all cloud resources.",
		dag.TaskKindInfraCI:         "You are an expert DevOps engineer. Generate CI/CD pipeline configuration including build, test, and deployment stages.",
		dag.TaskKindCrossCutTesting: "You are an expert test engineer. Generate test scaffolding including unit tests, integration tests, and E2E test setup. Use table-driven tests and the RED-GREEN-REFACTOR TDD cycle. Target 80%+ coverage on business logic.",
		dag.TaskKindCrossCutDocs:    "You are an expert technical writer. Generate API documentation, OpenAPI specs, and changelog files.",
	}

	desc, ok := descriptions[kind]
	if !ok {
		desc = "You are an expert software engineer. Generate production-quality code based on the provided specifications."
	}

	return "## Role\n\n" + desc
}

// outputFormatInstructions describes the required response format to the agent.
func outputFormatInstructions() string {
	return `## Output Format

You MUST respond with a <files> block containing a JSON array of file objects.
Each file object has a "path" (relative to the project output directory) and "content" (complete file content).

Example:
<files>
[
  {
    "path": "services/user-api/main.go",
    "content": "package main\n\nimport ..."
  },
  {
    "path": "services/user-api/Dockerfile",
    "content": "FROM golang:1.26-alpine\n..."
  }
]
</files>

Rules:
- Always use the <files>...</files> XML tags — do NOT use markdown code fences for the file list.
- Include ALL files needed for the task to be complete and buildable.
- File paths must use forward slashes and be relative (no leading slash).
- File content must be complete — no placeholders, no TODO comments for required logic.
- For Go: include go.mod with correct module paths and all imports.
- For TypeScript/JS: include package.json and all necessary config files.
- For Terraform: include all .tf files needed to apply successfully.
- Generated code must pass the relevant linter/build check for its language.
- For Go services: always generate _test.go files alongside every service, handler, and repository file. Use table-driven tests covering happy path, error cases, and edge cases.
- No hardcoded secrets: read all credentials from environment variables with a startup check (if os.Getenv("KEY") == "" { log.Fatal("KEY not configured") }).
- Apply idiomatic Go: constructor injection, small focused interfaces, error wrapping with fmt.Errorf("context: %w", err). Never ignore errors.
- All Go code must be gofmt-clean — use standard Go indentation and formatting.`
}
