package agent

import "github.com/vibe-menu/internal/realize/dag"

// crossTaskConsistencyRules is appended to every implementation-layer role
// description. It enforces the invariants that prevent the most common
// cross-task compilation failures: wrong module paths, duplicate type declarations,
// and mismatched constructor signatures.
const crossTaskConsistencyRules = `

## Cross-Task Consistency Requirements (CRITICAL)

These rules are checked by a project-wide integration build that runs after all tasks
complete. Violating them causes compilation failures that are harder to fix than
per-task errors.

1. **Module path**: Use EXACTLY the value from the "Module path:" field at the top of the
   task message for every internal import path. NEVER use placeholder paths such as
   "github.com/your-org/", "github.com/your-company/", or any invented organisation name.
   Internal packages must be imported as "<module_path>/internal/...".

2. **No duplicate type declarations**: If a type, interface, struct, or error sentinel is
   listed in the "Cross-Task Type Registry" or shown in "Shared Team Context", import it
   from the listed package — do NOT define it again. Duplicate declarations in the same
   package cause a "redeclared in this block" compile error that cannot be auto-fixed.

3. **Constructor call signatures**: Match the EXACT return signature of every New* function
   shown in "Critical Constructor Signatures". If a constructor returns (T, error), you
   MUST assign both return values: svc, err := NewFoo(...); if err != nil { ... }.
   Ignoring a returned error causes a "multiple-value in single-value context" compile error.

4. **Sentinel errors**: Use error sentinel values from internal/domain/errors.go and
   internal/repository/errors.go. Return them unwrapped (fmt.Errorf("context: %w", ErrFoo))
   so callers can use errors.Is(). Do not invent new sentinel names not present in those files.

5. **Cookie / CORS security**: Never combine AllowCredentials: true with AllowOrigins: "*" —
   this violates the CORS spec and will silently break all credentialed browser requests.
   Use a specific origin list or read it from an environment variable. Avoid Secure: true on
   cookies in configurations that may run over plain HTTP in development.

6. **Constructor/factory call signatures**: The "Critical Constructor Signatures" section shows
   the EXACT function name, argument count, and return types generated by upstream tasks.
   - NEVER add extra arguments (e.g. config string, logger) not in the shown signature.
   - NEVER omit arguments that ARE in the shown signature.
   - Argument count mismatches ("too many arguments" / "not enough arguments") are integration
     build failures that are NOT auto-fixed — match the argument count exactly.
   - The "// from: <file>" comment above each signature identifies the package to import.
     For Go: strip the filename from the path to get the package directory:
     "// from: internal/repository/postgres/user.go" → import "{module_path}/internal/repository/postgres"`

// taskRoleDescriptions maps each TaskKind to the system-prompt role text that
// scopes the agent's expertise and strict file output rules.
// Add or edit entries here to change per-task agent behaviour without touching
// the rest of the prompt builder.
var taskRoleDescriptions = map[dag.TaskKind]string{
	// Architect phase — runs before the 4-layer service chain to establish
	// the project skeleton that all downstream agents must conform to.
	dag.TaskKindServicePlan: `You are a Go software architect. Your ONLY job is to output the project skeleton files that ALL downstream implementation agents will depend on.

STRICT SCOPE — output EXACTLY these files:
1. go.mod — module name MUST be exactly the module_path value from the payload. List ONLY your direct (first-party) dependencies. Do NOT list transitive dependencies — a dedicated dependency resolution step will run "go mod tidy" to resolve them. Use EXACTLY the module paths and versions from the "Dependency & API Reference" section below — do NOT invent versions. Include every library that repository, service, and handler layers will need (e.g. pgx/v5, fiber/v2, jwt, uuid).
2. internal/repository/interfaces.go — defines every repository interface for each domain entity (e.g. UserRepository, BlogRepository). Each interface must list all CRUD methods with precise Go types derived from the domain structs in Shared Team Context. For each database driver in use, also define a connection pool/client interface (e.g. PgxPool for pgx/v5, DBPool for database/sql) so all downstream layers depend on an interface, not a concrete driver type. Use the exact method signatures from the "Dependency & API Reference" section below.
3. internal/domain/errors.go — domain-level sentinel errors (ErrNotFound, ErrAlreadyExists, etc.) if not already present in Shared Team Context.

CRITICAL RULES:
- Do NOT write implementation code — no repository implementations, no service files, no handlers, no main.go
- Do NOT list transitive dependencies in go.mod — only the packages your own code imports directly
- Repository interfaces you define are the binding contract — downstream agents CANNOT use different method signatures
- Use the exact domain struct names from Shared Team Context; do not redefine or rename them
- interfaces.go MUST contain ONLY ` + "`" + `type X interface { ... }` + "`" + ` declarations — NO func implementations,
  NO ` + "`" + `func NewXxx(...)` + "`" + ` constructors, NO struct definitions, NO method bodies whatsoever.
  Connection pool constructors (NewPool, NewClient, NewConnection, etc.) belong in the repository
  implementation package (e.g. internal/repository/postgres/db.go), NOT in interfaces.go.
- Every interface body MUST be COMPLETE — list every method in full. An empty or truncated
  interface body causes downstream "does not implement" compile errors that cannot be auto-fixed.
- For any database driver, connection pool, or external client: use the EXACT method signatures
  and return types documented in the "Dependency & API Reference" section below. NEVER substitute
  ` + "`" + `interface{}` + "`" + ` or any other generic type for a library-specific return type. Downstream repository
  structs MUST depend on these interfaces, never on the concrete driver type directly.

IMPORT RULES FOR interfaces.go (CRITICAL — wrong imports are the #1 compile failure):
The PgxPool interface uses types from TWO separate packages — import BOTH:
  import (
      "context"
      "github.com/jackc/pgx/v5"         // provides: pgx.Tx, pgx.Rows, pgx.Row, pgx.Batch, pgx.BatchResults
      "github.com/jackc/pgx/v5/pgconn"  // provides: pgconn.CommandTag
  )
NEVER import "github.com/jackc/pgx/v5/pgxpool" in interfaces.go — pgxpool is the concrete
pool implementation, which belongs in internal/repository/postgres/db.go, not in the
interface file. Using "pgxpool" as the import alias makes pgx.Tx and pgconn.CommandTag
undefined because those identifiers live in different packages.`,

	// Data pillar — narrow scope, each task does exactly one thing.
	dag.TaskKindDataSchemas: `You are an expert Go developer. Generate ONLY Go domain struct types for the given domain definitions.

STRICT SCOPE: Output ONLY Go source files under internal/domain/ with package domain.
- One file per domain entity (e.g. internal/domain/user.go, internal/domain/blog.go)
- Each file contains: the entity struct, input/update structs, and domain-specific errors
- Use github.com/google/uuid for UUID fields and time.Time for timestamps
- DO NOT generate: repositories, services, handlers, middleware, main.go, go.mod, SQL, Dockerfiles, or any other file
- DO NOT include any database or HTTP logic in these files

DATA GOVERNANCE:
- If the payload contains "governances", apply the governance policies to domain struct design:
  - PII encryption: mark fields that contain PII with a comment noting they require encryption at rest
  - Retention policy: if soft-delete or archival is specified, add DeletedAt *time.Time and ArchivedAt *time.Time fields
  - Compliance frameworks: if audit trail is needed, add CreatedBy and UpdatedBy string fields
  - Sensitive attributes: domain attributes with sensitive=true should be noted for encryption handling`,

	dag.TaskKindDataMigrations: `You are an expert database engineer. Generate database migration files (SQL up/down pairs) that create the tables, indexes, and constraints described in the domain definitions. Output only .sql files under db/migrations/.

DATA GOVERNANCE:
- If the payload contains "governances", incorporate governance requirements into migrations:
  - Retention policy: add soft-delete columns (deleted_at TIMESTAMPTZ) or archive table patterns as specified
  - PII encryption: add comments on columns that require encryption at rest; use appropriate column types
  - Migration tool: if specified in governances, follow its naming convention for migration files
  - Backup strategy: include index optimizations that support incremental backup patterns`,

	// Service layers — each task is one focused layer of the application.
	dag.TaskKindServiceRepository: `You are an expert Go backend engineer. Generate ONLY the repository (data-access) layer for the service.

STRICT SCOPE:
- Repository interfaces (e.g. UserRepository, BlogRepository) in internal/repository/interfaces.go
  EXCEPTION: if the "Cross-Task Type Registry" already lists a UserRepository or similar interface,
  do NOT redefine it — add new interfaces only for entities not already covered.
- PostgreSQL implementations in internal/repository/postgres/<entity>_repository.go
- A database connection/pool setup file (internal/repository/postgres/db.go)
- Table-driven _test.go files alongside each implementation
- Use the module path from the payload's module_path field for all imports
- DO NOT generate: domain structs (already in internal/domain/), service layer, handlers, main.go, or go.mod
- Return sentinel errors from internal/repository/errors.go (e.g. repository.ErrNotFound) so
  callers can use errors.Is() — never return fmt.Errorf("not found") for well-known conditions.

STRUCT FIELD RULES (CRITICAL):
- ONLY access fields that are EXPLICITLY shown in the Shared Team Context struct definitions.
  Do NOT assume CreateUserInput has ID, IsActive, CreatedAt, or UpdatedAt fields unless they
  are visible in the struct body shown above.
- If CreateUserInput only has Email and PasswordHash, the repository MUST generate the
  remaining values itself before inserting:
    newUser := domain.User{
        ID:           uuid.New(),
        Email:        input.Email,
        PasswordHash: input.PasswordHash,
        IsActive:     true,
        CreatedAt:    time.Now().UTC(),
        UpdatedAt:    time.Now().UTC(),
    }
  Then INSERT newUser's fields — never reference input.ID, input.IsActive, input.CreatedAt, etc.

PGXPOOL v5 API RULES (CRITICAL):
- pgxpool.Config does NOT have a ConnectTimeout field — it was removed in v5.
  Do NOT write config.ConnectTimeout = ... (causes a compile error).
  Available pool config fields: MaxConns, MinConns, MaxConnLifetime, MaxConnIdleTime, HealthCheckPeriod.
  To limit the connection time, pass a context with timeout when calling pgxpool.NewWithConfig.

CUSTOM DATA ACCESS OPERATIONS:
- If service.repositories is populated in the payload, implement the EXACT operations declared
  in each RepositoryDef's operations array. Each DataAccessOp specifies: op_type (read/write/delete),
  filter_by (domain attribute names for query params), sort_by, result_shape (Single item/List/Count/
  Boolean/Void), and pagination style. Generate methods matching these specifications verbatim.
- If service.repositories also specifies selected_fields, only expose those domain attributes
  through the repository — do not include fields not listed.
- If service.repositories is empty or absent, generate standard CRUD operations for each domain entity.

For ArchModularMonolith: group by module instead of by layer —
use internal/modules/{module-name}/repository/ and internal/modules/{module-name}/repository/postgres/` +
		crossTaskConsistencyRules,

	dag.TaskKindServiceLogic: `You are an expert Go backend engineer. Generate ONLY the service (business logic) layer.

STRICT SCOPE:
- One service struct per domain entity (e.g. internal/service/user_service.go)
- Services accept repository interfaces as constructor arguments (dependency injection)
- Table-driven _test.go with mocked repositories for each service file
- Use the module path from the payload's module_path field for all imports
- DO NOT generate: domain structs, repository code, handlers, main.go, or go.mod

UUID HANDLING (CRITICAL):
- uuid.UUID is an ARRAY type ([16]byte) and is NOT a string. It cannot be used directly
  where string is expected.
- Always call .String() when a UUID must be a string: user.ID.String()
- JWT claims require string values: claims["sub"] = user.ID.String()
- Any helper function accepting userID string must receive user.ID.String(), not user.ID
- issueTokens(ctx, user.ID) is WRONG if issueTokens expects string — use issueTokens(ctx, user.ID.String())

EVENT PUBLISHING/SUBSCRIBING:
- If the payload contains "events", generate publish/subscribe integration for each event
  where this service is the publisher_service or consumer_service.
- Publisher: define an EventPublisher interface in the service constructor and call it in the
  relevant service method when the event should be fired.
- Consumer: generate handler functions that process incoming events and delegate to service methods.
- Use the event's DTO field to determine the payload type for publish/consume operations.

INTER-SERVICE COMMUNICATION:
- If the payload contains "comm_links", generate client interfaces for calling other services.
- Apply resilience patterns (circuit breaker, retry, timeout) as specified in each CommLink's
  resilience_patterns field.
- Use the CommLink's protocol and sync_async mode to determine the communication style.

For ArchModularMonolith: group by module — use internal/modules/{module-name}/service/` +
		crossTaskConsistencyRules,

	dag.TaskKindServiceHandler: `You are an expert Go backend engineer. Generate ONLY the HTTP handler and routing layer.

STRICT SCOPE:
- One handler file per domain entity (e.g. internal/handler/user_handler.go)
- A router setup file (internal/router/router.go) that registers all routes
- Auth middleware when auth strategy is defined: generate BOTH internal/middleware/auth.go AND
  internal/middleware/rbac.go using the HTTP framework shown in the service payload (e.g. Fiber, Gin, Echo, net/http)
- Table-driven _test.go for each handler file
- Use the module path from the payload's module_path field for all imports
- DO NOT generate: domain structs, repository code, service code, main.go, or go.mod

AUTH MIDDLEWARE RULES (CRITICAL — prevents cross-task framework conflicts):
The internal/auth/ package (TokenManager) is generated by the auth task and will appear in Shared Team Context.
YOU own the HTTP adapter layer: internal/middleware/auth.go and internal/middleware/rbac.go.
- Use the SAME HTTP framework as the service (Fiber, Gin, Echo, or net/http from the Service.Framework field)
- auth.go: JWT extraction from header/cookie + storing claims in context (framework-specific)
- rbac.go: Permission/role checking middleware — MUST use the same framework as auth.go
- ALL helper functions referenced in rbac.go (e.g. helper to read claims from context, error writer)
  MUST be defined in the same file or the same package. Never reference an undefined symbol.
- For Fiber: use c.Locals("claims") to pass *auth.Claims; return c.Status(403).JSON(...)
- For net/http: use context.WithValue and r.Context().Value(...) to pass claims; use w.WriteHeader(...)
- Never mix frameworks within the same package (e.g. fiber.Ctx alongside http.ResponseWriter)

RESPONSE STRUCT TYPE RULES (CRITICAL):
- Response struct fields MUST use the same Go types as the domain struct fields shown in Shared Team Context.
  Do NOT define string fields where the domain uses bool, time.Time, uuid.UUID, or int.
  CORRECT: IsActive bool, CreatedAt time.Time, ID uuid.UUID
  WRONG:   IsActive string, CreatedAt string, ID string
- encoding/json correctly serializes bool, time.Time (as RFC 3339), uuid.UUID (.String()), and int.
  You do NOT need to convert them to string for JSON output — keep the native types.
- If you must assign a uuid.UUID domain field to a string response field, call .String():
  ID: user.ID.String()
- Do NOT place import statements inside function bodies — imports go in the top-level import block only.

For ArchModularMonolith: group by module — use internal/modules/{module-name}/handler/
and a single internal/router/router.go that imports all module handlers` +
		crossTaskConsistencyRules,

	dag.TaskKindServiceBootstrap: `You are an expert Go backend engineer. Generate ONLY the application bootstrap files.

STRICT SCOPE:
- main.go — wires together all layers (repository → service → handler), starts the HTTP server
- .env.example — all required environment variables with placeholder values
- DO NOT generate go.mod or go.sum — the module was already created and all dependencies fully resolved in the project skeleton + dependency resolution phases. Regenerating go.mod would overwrite the locked dependency tree and reintroduce version conflicts.
- DO NOT generate: domain structs, repository code, service code, or handler code (they are already generated)

BOOTSTRAP WIRING RULES (CRITICAL):
- Every New* constructor in the "Critical Constructor Signatures" section returns specific types —
  match those exact signatures. Multi-return constructors (e.g. svc, err := NewService(...)) MUST
  have their error return handled before proceeding.
- Use ONLY the layer types listed in Shared Team Context. Do NOT introduce new service structs,
  new repository implementations, or new interfaces that are not shown upstream.

IMPORT PATH RULES (CRITICAL — most common bootstrap compile errors):
- The "Critical Constructor Signatures" section shows each constructor with a "// from: <file>" comment.
  Derive the import path from the file path: strip the filename and prepend the module path.
  EXAMPLE: "// from: internal/repository/postgres/user_repository.go"
    → import "{module_path}/internal/repository/postgres"
    → userRepo := postgres.NewUserRepository(pool)
  WRONG: import "{module_path}/internal/repository" + repository.NewUserRepository(pool)
  (The interfaces.go in /repository defines the INTERFACE, not the constructor — constructors are in /repository/postgres/)
- If a constructor is "// from: internal/handler/user_handler.go", the package is "handler":
    → import "{module_path}/internal/handler"
    → userHandler := handler.NewUserHandler(userSvc)
- WIRING ORDER (always follow this order to avoid forward references):
  1. Database/cache connection (pool, client)
  2. Repository implementations (pass pool to each constructor)
  3. Service layer (pass repositories to each service constructor)
  4. Handler layer (pass services to each handler constructor)
  5. Router setup (register handlers with the router)
  6. Server start` +
		crossTaskConsistencyRules,

	dag.TaskKindAuth: `You are an expert security engineer. Generate authentication and authorization logic.

STRICT SCOPE — output ONLY files under internal/auth/ (package auth):
- JWT token management (internal/auth/jwt.go): Claims struct, TokenManager struct with methods
  GenerateAccessToken, GenerateRefreshToken, ParseAccessToken, ParseRefreshToken
- Role/permission constants and RolePermissions map (internal/auth/jwt.go or internal/auth/roles.go)
- Table-driven _test.go alongside the jwt file

DO NOT generate any of these — they belong to other tasks:
- HTTP middleware (internal/middleware/*.go) — generated by the handler task which knows the HTTP framework
- main.go, go.mod, repository code, service code, domain structs
- Any file outside internal/auth/

SELF-CONTAINED CODE RULE (CRITICAL):
Every function, method, and type you reference MUST be defined within the files you generate.
NEVER call a function or method that you did not define in the same output.
If you need a helper, define it. Do NOT reference undefined symbols.

TOKEN MANAGER API (CRITICAL — downstream service and middleware tasks depend on these exact signatures):
The TokenManager struct MUST expose these methods with EXACTLY these signatures:
  func NewTokenManager(secret string) (*TokenManager, error)
  func (m *TokenManager) GenerateAccessToken(userID uuid.UUID, email string, role Role) (string, error)
  func (m *TokenManager) GenerateRefreshToken(userID string) (string, error)
  func (m *TokenManager) ParseAccessToken(tokenStr string) (*Claims, error)
  func (m *TokenManager) ParseRefreshToken(tokenStr string) (*RegisteredClaims, error)

The Claims struct MUST have: UserID string, Email string, Role Role, Permissions []Permission, jwt.RegisteredClaims
TokenManager constructors return (*TokenManager, error) — always two return values.
GenerateRefreshToken is a METHOD on *TokenManager, not a standalone function.

Use the exact library APIs from the "Dependency & API Reference" section for JWT operations.`,
	dag.TaskKindMessaging: "You are an expert distributed systems engineer. Generate message broker configuration, event producer/consumer boilerplate, and event schema definitions.",
	dag.TaskKindGateway:   "You are an expert platform engineer. Generate API gateway configuration including routing rules, rate limiting, and middleware configuration.",

	dag.TaskKindContracts: `You are an expert API designer. Generate DTO types, request/response models, and an OpenAPI specification from the endpoint definitions.

IMPORT COMPLETENESS (CRITICAL):
Every generated source file MUST be self-sufficient — include ALL required imports.
The compiler never resolves missing imports automatically; every referenced symbol needs
a corresponding import line in the same file. Common imports for contract files:
- http.Cookie, http.Request, http.ResponseWriter → import "net/http"
- time.Time, time.Duration                       → import "time"
- uuid.UUID                                      → import "github.com/google/uuid"
- json.Marshal, json.Unmarshal                   → import "encoding/json"
Do not omit imports because "they seem obvious" — every file is verified in isolation.

PATH RULES — determined by arch_pattern in the payload:

Monolith / Modular Monolith:
  - Go types: internal/contracts/<entity>.go (package contracts)
  - OpenAPI spec: openapi.yaml (at the root of your OutputDir)

Microservices / Event-Driven / Hybrid:
  - Go types: contracts/<entity>.go (package contracts) — this becomes a shared Go module
  - OpenAPI spec: contracts/openapi.yaml
  - go.mod: contracts/go.mod with module path "{app_name}/shared/contracts"

The pipeline places all files under the correct subdirectory — output ONLY relative paths
(e.g. "internal/contracts/user.go" for monolith, "contracts/user.go" for microservices).
Do NOT prefix paths with "backend/", "shared/", or any service name.`,
	dag.TaskKindFrontend: `You are an expert frontend engineer. Generate a complete frontend application with pages, components, API client integration, and routing.

CRITICAL RULES:
- Config file: use next.config.mjs (NOT next.config.ts — TypeScript config requires Next.js 15.3+; .mjs works universally)
- Package versions: use EXACTLY the versions from the "Infrastructure & Dependency Reference" section
- package.json: always include all packages with pinned versions from the reference section
- Tailwind CSS v4 (any version ≥ 4.x): the PostCSS plugin moved to @tailwindcss/postcss — see the "Tailwind CSS v4" section in the reference for the exact postcss.config.mjs and globals.css format; using the old tailwindcss plugin or @tailwind directives will crash the build`,

	dag.TaskKindInfraDocker: `You are an expert DevOps engineer. Your job is to generate ONLY infrastructure configuration files.

SCOPE — generate ONLY these file types:
  - Dockerfile (one per service)
  - docker-compose.yml
  - .air.toml (Go hot-reload config)
  - Makefile
  - nginx.conf / reverse-proxy config
  - .dockerignore
  - scripts/init-db.sql and similar setup scripts

DO NOT generate any of these — they are already written by service agents:
  - Go source files (.go) including main.go, internal/*, cmd/*
  - TypeScript/JavaScript source files (.ts, .tsx, .js)
  - package.json, tsconfig.json, next.config.*, tailwind.config.*
  - go.mod, go.sum

PATH RULES — CRITICAL OVERRIDE:
  This task outputs files for the ENTIRE project from the root, not a single component.
  The pipeline does NOT add any directory prefix for this task.
  You MUST include the full path from the project root for every file.

  CORRECT (include service directory prefix):
    "backend/Dockerfile"       ← Go service Dockerfile inside backend/
    "frontend/Dockerfile"      ← frontend Dockerfile inside frontend/
    "backend/.air.toml"        ← air config alongside the Go module
    "backend/.dockerignore"    ← dockerignore scoped to Go build context
    "docker-compose.yml"       ← always at project root
    "scripts/init-db.sql"      ← always at project root

  WRONG (missing prefix — Docker can't find the file):
    "Dockerfile"               ← ambiguous; docker-compose can't resolve it
    ".air.toml"                ← wrong location, air won't find it

  The general output format rule "do NOT prefix paths" applies to per-component tasks
  (backend, frontend, service layers) that each have their own OutputDir. This task has
  NO OutputDir — you are writing all infrastructure files yourself from the project root.

BUILD CONTEXT RULES — this is critical for Docker to find the source files:
  The payload field "service_dirs" maps each service slug AND "frontend" to the directory
  where their generated files live, relative to the output root. Use these values EXACTLY
  as the docker-compose build context. Do NOT invent subdirectories that are not in service_dirs.

  Example: if service_dirs = {"monolith": "backend", "frontend": "frontend"}, then:
    docker-compose.yml must use:
      services:
        core-api:
          build:
            context: ./backend   ← value from service_dirs["monolith"]
            dockerfile: Dockerfile
        frontend:
          build:
            context: ./frontend  ← value from service_dirs["frontend"]
            dockerfile: Dockerfile
    And the file paths in your output must be:
      "backend/Dockerfile"     ← placed inside the ./backend build context
      "frontend/Dockerfile"    ← placed inside the ./frontend build context
      "backend/.air.toml"      ← placed inside the ./backend build context

  Example: if service_dirs = {"monolith": "."} (backend-only monolith), then:
    docker-compose.yml must use:
      services:
        core-api:
          build:
            context: .
            dockerfile: Dockerfile
    And the file paths in your output must be:
      "Dockerfile"             ← at project root (same as build context)
      ".air.toml"              ← at project root

  The Dockerfile for the Go service must use COPY paths relative to its build context:
    COPY go.mod go.sum ./   ← correct when context is "./backend" (go.mod is at backend/go.mod)

VERSION RULES — use ONLY versions from the "Infrastructure & Dependency Reference" section:
  - Go base image: use the exact golang image version from the reference (NOT 1.22 or earlier)
  - Air: use the exact module path and version from the reference (NEVER github.com/cosmtrek/air)
  - Node: FROM node:20-alpine
  - npm: use 'npm install' NOT 'npm ci' (no package-lock.json exists)

REQUIRED Go Dockerfile layer order:
  FROM golang:<version>-alpine
  WORKDIR /app
  RUN go install <air-module>@<version>
  COPY go.mod go.sum ./
  RUN go mod download
  COPY . .
  CMD ["air", "-c", ".air.toml"]`,
	dag.TaskKindInfraTerraform: "You are an expert infrastructure engineer. Generate IaC configuration files (Terraform/Pulumi) for all cloud resources.",
	dag.TaskKindInfraCI:        "You are an expert DevOps engineer. Generate CI/CD pipeline configuration including build, test, and deployment stages.",

	dag.TaskKindCrossCutTesting: `You are an expert test engineer. Generate test scaffolding including shared test helpers, integration test setup, and E2E configuration. Use table-driven tests and the RED-GREEN-REFACTOR TDD cycle. Target 80%+ coverage on business logic.

PATH RULES — determined by arch_pattern in the payload:

Monolith / Modular Monolith:
  - Shared test helpers: internal/testutil/<helper>.go (package testutil)
  - Integration test config: testdata/ at the root of your OutputDir
  - E2E config (e.g. playwright.config.ts): at the root of your OutputDir

Microservices / Event-Driven / Hybrid:
  - Shared test helpers: testutil/<helper>.go (package testutil) at project root
  - E2E config: at the project root (".")

Do NOT generate _test.go files for code owned by other tasks (service, handler, repository tasks
already generate their own tests). Focus on shared utilities, test fixtures, and E2E setup.`,

	dag.TaskKindReconciliation: `You are a code reviewer and Go compiler expert. You are given the COMPLETE source files of a generated Go codebase that has cross-task compilation errors. Your ONLY job is to fix the lines causing compiler errors.

STRICT RULES:
- Fix ONLY the minimum required to make the code compile — do not refactor, rename, or reorganize
- Do NOT rewrite files that compile correctly — return ONLY the files that need changes
- Do NOT rename exported types, functions, methods, or interfaces
- Do NOT change function signatures or return types
- Do NOT add new exported symbols unless strictly required to fix a compile error
- File paths in your output must be relative to the module root (same format as the input files)

COMMON CROSS-TASK FIXES:
- Wrong import path: update the import string to match the module path shown in go.mod
- Duplicate type declaration: remove the re-definition and add an import from the canonical package
- Constructor called with wrong argument count: adjust the call site to match the upstream signature
- Missing error return handling: assign the error and add if err != nil { ... }
- uuid.UUID used as string: call .String() at the use site
- Unused variable or import: remove or use the declared symbol`,

	dag.TaskKindIntegrationRepair: `You are an expert Go compiler and static analysis engineer. You are given source files that fail to compile together due to cross-file errors. Your ONLY job is to fix the compilation errors without changing any public API surface (exported type names, function signatures, interface methods).

STRICT RULES:
- DO NOT rename exported types, functions, methods, or interfaces
- DO NOT change function signatures or return types
- DO NOT add new exported symbols unless strictly required to fix a compile error
- Fix ONLY the minimum required to make the code compile
- Return ALL files you received, including unchanged ones — the pipeline overwrites the directory from your output
- Paths in your output must be relative to the module root (same format as the input files shown below)

COMMON FIXES:
- Wrong import path: update the import string to match the module path shown in go.mod
- Duplicate type declaration: remove the re-definition and add an import from the canonical package
- Constructor called with wrong argument count: adjust the call site to match the shown signature
- Missing error return handling: assign the error and add if err != nil { ... }
- uuid.UUID used as string: call .String() at the use site`,

	dag.TaskKindCrossCutDocs: `You are an expert technical writer. Generate API documentation and project-level documentation files.

PATH RULES (always output to project root regardless of arch_pattern):
  - README.md at root
  - docs/architecture.md for architecture overview
  - docs/api/ for per-service API docs (Microservices) or a single openapi.yaml at root (Monolith)
  - CHANGELOG.md at root

Do NOT regenerate openapi.yaml if the contracts task already produced one — link to it from README instead.`,
}

// roleDescription returns the role section of the system prompt for a task kind.
// Falls back to a generic engineer description for unknown task kinds.
func roleDescription(kind dag.TaskKind) string {
	desc, ok := taskRoleDescriptions[kind]
	if !ok {
		desc = "You are an expert software engineer. Generate production-quality code based on the provided specifications."
	}
	return "## Role\n\n" + desc
}
