//go:build ignore

package agent

// This file shows the KEY CHANGES to prompt.go. Merge these into your existing prompt.go.
//
// Changes:
// 1. SystemPrompt now accepts a depsContext string with library API docs + version refs
// 2. UserMessage tells downstream tasks not to regenerate go.mod when a locked one exists
// 3. outputFormatInstructions has stronger go.mod rules

import (
	"fmt"
	"strings"

	"github.com/vibe-menu/internal/realize/dag"
	"github.com/vibe-menu/internal/realize/deps"
	"github.com/vibe-menu/internal/realize/skills"
)

// SystemPromptV2 builds the system prompt with library API docs injected.
// depsContext is generated by deps.PromptContext() based on the task's technology stack.
func SystemPromptV2(kind dag.TaskKind, skillDocs []skills.Doc, depsContext string) string {
	var b strings.Builder

	b.WriteString(roleDescription(kind))
	b.WriteString("

")
	b.WriteString(outputFormatInstructionsV2())

	// ── NEW: inject dependency & API reference ──
	if depsContext != "" {
		b.WriteString("
")
		b.WriteString(depsContext)
	}

	if len(skillDocs) > 0 {
		b.WriteString("

## Technology Skill Guides

")
		for _, doc := range skillDocs {
			b.WriteString(fmt.Sprintf("### %s

%s

", doc.Technology, doc.Content))
		}
	}

	return b.String()
}

// BuildDepsContext creates the dependency context string for a task's prompt.
// Call this in the orchestrator when setting up the agent context.
func BuildDepsContext(task *dag.Task) string {
	var framework string
	var technologies []string

	if task.Payload.Service != nil {
		framework = task.Payload.Service.Framework
		technologies = append(technologies, task.Payload.Service.Language)
		for _, db := range task.Payload.Databases {
			technologies = append(technologies, string(db.Type))
		}
		if task.Payload.Auth != nil {
			technologies = append(technologies, task.Payload.Auth.Strategy)
		}
	}

	if framework == "" && len(technologies) == 0 {
		return ""
	}

	return deps.PromptContext(framework, technologies)
}

// outputFormatInstructionsV2 is the improved version with stronger go.mod rules.
func outputFormatInstructionsV2() string {
	return `## Output Format

You MUST respond with a <files> block containing a JSON array of file objects.
Each file object has a "path" (relative to the project output directory) and "content" (complete file content).

Example:
<files>
[
  {
    "path": "services/user-api/main.go",
    "content": "package main

import ..."
  }
]
</files>

Rules:
- Always use the <files>...</files> XML tags — do NOT use markdown code fences for the file list.
- Include ALL files needed for the task to be complete and buildable.
- File paths must use forward slashes and be relative (no leading slash).
- File content must be complete — no placeholders, no TODO comments for required logic.

### Go-Specific Rules (CRITICAL)
- If a go.mod was provided in the "Shared Team Context" or "LOCKED DEPENDENCIES" section,
  DO NOT include go.mod or go.sum in your output. The build system manages dependencies.
- If you MUST generate go.mod (first task only), use EXACTLY the module paths and versions
  from the "Dependency Version Reference" section. Never invent version strings.
- All Go regex patterns MUST use backtick raw strings, not double-quoted strings:
  CORRECT: regexp.MustCompile(` + "`" + `\d{4}-\d{2}-\d{2}` + "`" + `)
  WRONG:   regexp.MustCompile("\d{4}-\d{2}-\d{2}")    // invalid escape sequences
  WRONG:   regexp.MustCompile("\d{4}-\d{2}-\d{2}") // works but fragile
- All Go code MUST be gofmt-clean. Use tabs for indentation, not spaces.
- Generate _test.go files for all handlers, services, and repositories.
- Use table-driven tests covering happy path, error cases, and edge cases.
- No hardcoded secrets — read all credentials from environment variables.
- Use the EXACT library APIs documented in the "Library API Reference" section.
  Do NOT invent types or functions that are not listed there.

### TypeScript-Specific Rules
- Include package.json with pinned dependency versions.
- Include tsconfig.json.

### General
- Generated code must pass the relevant linter/build check for its language.`
}
