package verify

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// TsVerifier runs `tsc --noEmit` on generated TypeScript projects.
// Degrades gracefully if `tsc` is not installed.
type TsVerifier struct{}

func NewTsVerifier() *TsVerifier { return &TsVerifier{} }

func (t *TsVerifier) Language() string { return "typescript" }

func (t *TsVerifier) Verify(ctx context.Context, outputDir string, files []string) (*Result, error) {
	tscPath, err := exec.LookPath("tsc")
	if err != nil {
		return &Result{Passed: true, Output: "tsc not found in PATH — skipping TypeScript verification"}, nil
	}

	// Find directories with tsconfig.json.
	dirs := tsConfigDirs(outputDir, files)
	if len(dirs) == 0 {
		return &Result{Passed: true, Output: "no tsconfig.json found — skipping TypeScript verification"}, nil
	}

	var combined bytes.Buffer
	allPassed := true

	for _, dir := range dirs {
		absDir := filepath.Join(outputDir, dir)
		out, err := runCmd(ctx, absDir, tscPath, "--noEmit")
		combined.WriteString(fmt.Sprintf("=== tsc --noEmit in %s ===\n%s\n", dir, out))
		if err != nil {
			allPassed = false
		}
	}

	return &Result{Passed: allPassed, Output: combined.String()}, nil
}

func tsConfigDirs(outputDir string, files []string) []string {
	seen := make(map[string]bool)
	dirs := []string{}

	// First pass: look for tsconfig.json in the generated file list.
	for _, f := range files {
		if filepath.Base(f) == "tsconfig.json" {
			dir := filepath.Dir(f)
			if !seen[dir] {
				seen[dir] = true
				dirs = append(dirs, dir)
			}
		}
	}

	// Second pass: if no tsconfig.json in generated files, scan the output directory
	// for tsconfig.json files (they may have been generated by a prior task or exist
	// as part of the project template).
	if len(dirs) == 0 {
		_ = filepath.Walk(outputDir, func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				if info != nil && info.IsDir() {
					name := info.Name()
					if name == "node_modules" || name == ".next" || strings.HasPrefix(name, ".") {
						return filepath.SkipDir
					}
				}
				return nil
			}
			if info.Name() == "tsconfig.json" {
				rel, relErr := filepath.Rel(outputDir, filepath.Dir(path))
				if relErr == nil && !seen[rel] {
					seen[rel] = true
					dirs = append(dirs, rel)
				}
			}
			return nil
		})
	}
	return dirs
}
